Repository smartdevicelink/sdl_security_ios, pull requests merged in 2019-10, with the labels that each got.

#22 Change documents directory to app support
  SDLSecurity/_SDLCertificateManager.m
Labels: bug

#21 Updated README
  README.md
Labels: enhancement

#27 Fixed downloading a certificate from a URL
  SDLSecurity/_SDLCertificateManager.h
  SDLSecurity/_SDLCertificateManager.m
  SDLSecurity/_SDLTLSEngine.m
  SDLSecurityTests/SDLCertificateManagerTests.m
Labels: enhancement

#31 Added a Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.mdPULL_REQUEST_TEMPLATE.md
Labels: enhancement

#32 Added an Issue Template
  .github/ISSUE_TEMPLATE.md
Labels: enhancement

#33 Fixed wrong pull request template name
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#35 Updated the OpenSSL license in the library documentation
  DEPENDENCIES.md
  third_party.md
Labels: documentation

#39 Consolidate private constants
  README.md
  SDLSecurity.xcodeproj/project.pbxproj
  SDLSecurity/SDLCertificateManager.h
  SDLSecurity/SDLCertificateManager.m
  SDLSecurity/SDLPrivateSecurityConstants.h
  SDLSecurity/SDLPrivateSecurityConstants.m
  SDLSecurity/SDLSecurityManager.m
  SDLSecurity/SDLTLSEngine.h
  SDLSecurity/SDLTLSEngine.m
  SDLSecurityTests/SDLCertificateManagerTests.m
  SDLSecurityTests/SDLTLSEngineTests.m
Labels: enhancement
