Repository smartdevicelink/sdl_security_ios, pull requests merged in 2021-07, with the labels that each got.

#54 Update SDLTLSEngine.m
  SDLSecurity/SDLTLSEngine.m
Labels: bug

#46 Data is now read from the SSL server until no more data is available
  SDLSecurity/SDLTLSEngine.h
  SDLSecurity/SDLTLSEngine.m
Labels: enhancement

#60 Change ASL Log to OSLog
  SDLSecurity.xcodeproj/project.pbxproj
  SDLSecurity.xcodeproj/xcshareddata/xcschemes/SDLSecurityStatic.xcscheme
  SDLSecurity/SDLSecurityLogger.m
Labels: bug

#61 v2.0.0 Release
  LICENSE
  README.md
  SDLSecurity.xcodeproj/project.pbxproj
  SDLSecurity.xcodeproj/xcshareddata/xcschemes/SDLSecurityStatic.xcscheme
  SDLSecurity/SDLCertificateManager.h
  SDLSecurity/SDLCertificateManager.m
  SDLSecurity/SDLPrivateSecurityConstants.h
  SDLSecurity/SDLPrivateSecurityConstants.m
  SDLSecurity/SDLSecurity.h
  SDLSecurity/SDLSecurityConstants.h
  SDLSecurity/SDLSecurityConstants.m
  SDLSecurity/SDLSecurityLogger.h
  SDLSecurity/SDLSecurityLogger.m
  SDLSecurity/SDLSecurityLoggerMacros.h
  SDLSecurity/SDLSecurityManager.h
  SDLSecurity/SDLSecurityType.h
  SDLSecurity/SDLTLSEngine.h
  SDLSecurity/SDLTLSEngine.m
Labels: release
